// Inline style objects shared across the Workout tab (routine list + builder).
export const styles = {
  header: {
    padding: '16px 16px 14px',
    borderBottom: '1px solid var(--border)',
    flexShrink: 0,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: 800,
    color: 'var(--text)',
  },
  startEmptyBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    padding: '14px 0',
    background: 'var(--accent)',
    border: 'none',
    borderRadius: 14,
    color: '#fff',
    fontSize: 16,
    fontWeight: 700,
    cursor: 'pointer',
  },
  sectionRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 16px 10px',
  },
  sectionLabel: {
    fontSize: 13,
    fontWeight: 700,
    color: 'var(--text3)',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  newRoutineBtn: {
    display: 'flex',
    alignItems: 'center',
    background: 'var(--bg2)',
    color: 'var(--accent)',
    border: '1px solid var(--border)',
    borderRadius: 10,
    padding: '6px 12px',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
  },
  routineList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    padding: '0 16px',
  },
  emptyState: {
    textAlign: 'center',
    color: 'var(--text3)',
    fontSize: 14,
    padding: '40px 16px',
  },

  // RoutineCard
  routineCard: {
    background: 'var(--bg2)',
    borderRadius: 14,
    border: '1px solid var(--border)',
    padding: '16px 16px 14px',
    position: 'relative',
  },
  menuWrap: {
    position: 'absolute',
    top: 12,
    right: 12,
    zIndex: 10,
  },
  dropMenu: {
    position: 'absolute',
    top: '100%',
    right: 0,
    background: 'var(--bg3)',
    border: '1px solid var(--border)',
    borderRadius: 10,
    minWidth: 160,
    boxShadow: '0 8px 32px rgba(0,0,0,0.4)',
    overflow: 'hidden',
    zIndex: 100,
  },
  menuItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    width: '100%',
    background: 'none',
    border: 'none',
    padding: '10px 14px',
    fontSize: 14,
    cursor: 'pointer',
    color: 'var(--text)',
  },
  confirmBtn: {
    background: 'var(--failure)',
    color: '#fff',
    border: 'none',
    borderRadius: 6,
    padding: '5px 10px',
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
  },
  cancelBtn: {
    background: 'var(--bg)',
    color: 'var(--text2)',
    border: 'none',
    borderRadius: 6,
    padding: '5px 10px',
    fontSize: 12,
    cursor: 'pointer',
  },
  routineTitle: {
    fontSize: 17,
    fontWeight: 700,
    color: 'var(--text)',
    marginBottom: 4,
    paddingRight: 32,
  },
  routineSub: {
    fontSize: 13,
    color: 'var(--text3)',
    marginBottom: 12,
  },
  chipsRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 14,
  },
  chip: {
    background: 'var(--bg3)',
    color: 'var(--text2)',
    borderRadius: 6,
    padding: '3px 8px',
    fontSize: 12,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    maxWidth: 130,
  },
  chipMore: {
    background: 'var(--bg3)',
    color: 'var(--text3)',
    borderRadius: 6,
    padding: '3px 8px',
    fontSize: 12,
  },
  cardActions: {
    display: 'flex',
    gap: 10,
  },
  primaryBtn: {
    display: 'flex',
    alignItems: 'center',
    background: 'var(--accent)',
    color: '#fff',
    border: 'none',
    borderRadius: 9,
    padding: '8px 18px',
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
    flex: 1,
    justifyContent: 'center',
  },
  ghostBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'transparent',
    color: 'var(--text2)',
    border: '1.5px solid var(--border)',
    borderRadius: 9,
    padding: '8px 18px',
    fontSize: 14,
    fontWeight: 500,
    cursor: 'pointer',
    flex: 1,
  },
  iconBtn: {
    background: 'none',
    border: 'none',
    padding: 6,
    cursor: 'pointer',
    borderRadius: 6,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Builder
  builderContainer: {
    height: '100%',
    background: 'var(--bg)',
    display: 'flex',
    flexDirection: 'column',
  },
  builderHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '16px 16px 14px',
    borderBottom: '1px solid var(--border)',
    flexShrink: 0,
  },
  backBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '4px 6px 4px 0',
    display: 'flex',
    alignItems: 'center',
  },
  builderHeaderTitle: {
    fontSize: 22,
    fontWeight: 800,
    color: 'var(--text)',
  },
  builderSection: {
    padding: '16px 16px 0',
  },
  routineNameInput: {
    width: '100%',
    background: 'var(--bg2)',
    border: '1.5px solid var(--border)',
    borderRadius: 10,
    color: 'var(--text)',
    fontSize: 16,
    fontWeight: 600,
    padding: '12px 14px',
    outline: 'none',
  },
  restRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 16px',
    borderBottom: '1px solid var(--border)',
  },
  restLabel: {
    display: 'flex',
    alignItems: 'center',
    fontSize: 14,
    color: 'var(--text2)',
  },
  restInputWrap: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  restInput: {
    width: 64,
    background: 'var(--bg2)',
    border: '1.5px solid var(--border)',
    borderRadius: 8,
    color: 'var(--text)',
    fontSize: 16,
    fontWeight: 600,
    padding: '6px 10px',
    textAlign: 'center',
    outline: 'none',
  },
  restUnit: {
    fontSize: 13,
    color: 'var(--text3)',
  },
  builderExList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    padding: '16px 16px 0',
  },
  builderEmptyState: {
    textAlign: 'center',
    color: 'var(--text3)',
    fontSize: 14,
    padding: '32px 16px',
  },
  builderCard: {
    background: 'var(--bg2)',
    borderRadius: 12,
    border: '1px solid var(--border)',
    padding: '14px 14px 10px',
  },
  builderCardHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 8,
    marginBottom: 10,
  },
  builderExName: {
    fontSize: 15,
    fontWeight: 600,
    color: 'var(--text)',
    marginBottom: 4,
  },
  bodyPartBadge: {
    background: 'var(--bg3)',
    color: 'var(--text3)',
    borderRadius: 5,
    fontSize: 11,
    padding: '2px 7px',
    textTransform: 'capitalize',
  },
  builderCardControls: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    flexShrink: 0,
  },
  setCountBadge: {
    fontSize: 11,
    color: 'var(--text3)',
    background: 'var(--bg3)',
    borderRadius: 5,
    padding: '2px 7px',
    marginRight: 4,
  },
  builderSetHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '0 4px',
    marginBottom: 6,
    fontSize: 11,
    color: 'var(--text3)',
    fontWeight: 600,
    letterSpacing: 0.5,
  },
  optsPanel: {
    background: 'var(--bg)',
    border: '1px solid var(--border)',
    borderRadius: 10,
    padding: '4px 12px',
    marginBottom: 12,
  },
  optRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    padding: '8px 0',
    borderBottom: '1px solid var(--border)',
  },
  optLabel: {
    fontSize: 13,
    color: 'var(--text2)',
    flexShrink: 0,
  },
  optSeg: {
    display: 'flex',
    background: 'var(--bg3)',
    borderRadius: 8,
    padding: 2,
    gap: 2,
  },
  optSegBtn: {
    padding: '5px 14px',
    borderRadius: 6,
    border: 'none',
    background: 'transparent',
    color: 'var(--text3)',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
  },
  optSegBtnActive: {
    background: 'var(--accent)',
    color: '#fff',
  },
  optNoteInput: {
    flex: 1,
    maxWidth: 200,
    background: 'var(--bg2)',
    border: '1.5px solid var(--border)',
    borderRadius: 8,
    color: 'var(--text)',
    fontSize: 16,
    padding: '6px 10px',
    outline: 'none',
    textAlign: 'right',
  },
  builderSetRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  builderSetNum: {
    width: 28,
    textAlign: 'center',
    fontSize: 13,
    color: 'var(--text2)',
    fontWeight: 600,
    flexShrink: 0,
  },
  setInput: {
    flex: 1,
    background: 'var(--bg)',
    border: '1.5px solid var(--border)',
    borderRadius: 8,
    color: 'var(--text)',
    fontSize: 16,
    padding: '7px 8px',
    textAlign: 'center',
    outline: 'none',
    minWidth: 0,
  },
  addSetBtn: {
    background: 'none',
    border: '1.5px dashed var(--border)',
    borderRadius: 8,
    color: 'var(--text3)',
    fontSize: 13,
    fontWeight: 500,
    width: '100%',
    padding: '8px 0',
    cursor: 'pointer',
    marginTop: 6,
  },
  addExerciseBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 'calc(100% - 32px)',
    margin: '20px 16px 0',
    padding: '13px 0',
    background: 'var(--bg2)',
    border: '1.5px solid var(--border)',
    borderRadius: 12,
    color: 'var(--text2)',
    fontSize: 15,
    fontWeight: 600,
    cursor: 'pointer',
  },
  saveBtn: {
    display: 'block',
    width: 'calc(100% - 32px)',
    margin: '14px 16px 0',
    padding: '14px 0',
    background: 'var(--accent)',
    border: 'none',
    borderRadius: 12,
    color: '#fff',
    fontSize: 16,
    fontWeight: 700,
    cursor: 'pointer',
    textAlign: 'center',
  },
};
